AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 512
      Timeout: 30
      CodeUri: hello-world
      Handler: lambda.handler
      Runtime: nodejs14.x
      Events:
        RootGet:
          Type: Api
          Properties:
            Path: /
            Method: get
  PollManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 512
      Timeout: 30
      CodeUri: poll-management
      Handler: lambda.handler
      Runtime: nodejs14.x
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              # https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazondynamodb.html
              - dynamodb:GetItem
              - dynamodb:PutItem
            Resource: !GetAtt PollingTable.Arn
      Environment:
        Variables:
          POLLINGTABLE: !Ref PollingTable
      Events:
        CreatePollEvent:
          Type: Api
          Properties:
            Path: /polls
            Method: put
        ReadPollEvent:
          Type: Api
          Properties:
            Path: /polls/{pollId}
            Method: get
  PollingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "pollId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pollId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      SSESpecification:
        SSEEnabled: true
Outputs:
  APIURL:
    Description: "API Endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  POLLINGTABLE:
    Description: "table"
    Value: !Ref PollingTable